Revert "drop '.NNNNN' random siffux from context key files"
This reverts commit 95049cd40114c31a9d3287d6aee1b549f452df72.

diff --git a/actions/context/put/action.yaml b/actions/context/put/action.yaml
--- a/actions/context/put/action.yaml
+++ b/actions/context/put/action.yaml
@@ -47,8 +47,15 @@ runs:
         CTX_VALUE: ${{ inputs.value }}
 
       run: |
-        # Put value into context key
-        printf "%s" "${CTX_VALUE}" > "${CTX_PATH}/${CTX_KEY}"
+        random="$(printf "%05d" "${RANDOM}")"
+        file_path="${CTX_PATH}/${CTX_KEY}.${random}"
+
+        if find "${CTX_PATH}" -name "${CTX_KEY}.[0-9][0-9][0-9][0-9][0-9][0-9]" | grep -vq '^$'; then
+          echo "::error::Key '${CTX_KEY}' already is set in context artifact"
+          exit 1
+        fi
+
+        printf "%s" "${CTX_VALUE}" > "${file_path}"
 
     - uses: actions/upload-artifact@v6
       with:
