add budle libs on linux for pl build, store symlinks for create archive action

diff --git a/blocks/pl/linux/test/action.yaml b/blocks/pl/linux/test/action.yaml
--- a/blocks/pl/linux/test/action.yaml
+++ b/blocks/pl/linux/test/action.yaml
@@ -12,6 +12,11 @@ inputs:
       Test command (initiate test for the platform)
     required: true
     default: 'go test ./...'
+  ext-programs-path:
+    description: |
+      The external_programs bootstrap script path.
+    required: false
+    default: 'external_programs'
   bootstrap-ci-script-name:
     description: |
       Bootstrap CI script name (install go modules, C++ libraries, binary tools, etc)
@@ -42,15 +47,6 @@ inputs:
       Must be used in conjunction with <test-integration-cache-paths>
     required: false
     default: ''
-  cdn-url:
-    description: |
-      CDN url for Static and Shared RockDB Libs.
-    required: false
-    default: 'https://cdn.mixcr.com/internal/pkgs'
-  rocksdb-version:
-    description:
-      RocksDB version.
-    required: true
 
   #
   # Github authentication control
@@ -84,26 +80,24 @@ runs:
     - name: Get runner metadata
       id: get_runner_metadata
       uses: milaboratory/github-ci/actions/shell@v4-beta
+      env:
+        PL_EXT_PROGRAMS_PATH: ${{ inputs.ext-programs-path }}
       with:
         run: |
-          get_os_arch=$(uname -m)
-          case "${get_os_arch}" in
-            x86_64)
-              _RUNNER_OS_ARCH="amd64"
-              ;;
-            aarch64 | arm64)
-              _RUNNER_OS_ARCH="arm64"
-              ;;
-            *)
-              echo "Arch is not in the list: ${get_os_arch}"
-              exit 1
-              ;;
-          esac
+          PL_EXT_PROGRAMS_PATH_SANITIZED=$(mish_sanitized "$PL_EXT_PROGRAMS_PATH")
 
-          _RUNNER_OS_SANITEZED=$(echo ${RUNNER_OS} | awk '{print tolower($0)}')
+          if [ -z "${PL_EXT_PROGRAMS_PATH_SANITIZED}" ];then
+            echo "ext-programs-path cannot be empty."
+            exit 1
+          else
+            PL_EXT_PROGRAMS_PATH="${GITHUB_WORKSPACE}/${PL_EXT_PROGRAMS_PATH_SANITIZED}"
+          fi
 
-          ghwa_set_output runner_os "${_RUNNER_OS_SANITEZED}"
-          ghwa_set_output runner_arch "${_RUNNER_OS_ARCH}"
+          PL_ROCKSDB_LIBS_PATH="${PL_EXT_PROGRAMS_PATH}/rocksdb-ci-libs"
+
+          # set envs
+          ghwa_set_env PKG_CONFIG_PATH "${PL_ROCKSDB_LIBS_PATH}/lib/pkgconfig"
+          ghwa_set_env LD_LIBRARY_PATH "${PL_ROCKSDB_LIBS_PATH}/lib"
 
     - name: Run boostrap ci script
       uses: milaboratory/github-ci/actions/shell@v4-beta
@@ -117,37 +111,6 @@ runs:
             printf "File: %s doesn't exist or it's not executable." "${CI_SCRIPT}"
             exit 1
           fi
-
-    - name: Download and unpack static and shared rocksdb libs
-      uses: milaboratory/github-ci/actions/shell@v4-beta
-      env:
-        GH_RUNNER_OS: ${{ fromJSON( steps.get_runner_metadata.outputs.data ).runner_os }}
-        GH_RUNNER_ARCH: ${{ fromJSON( steps.get_runner_metadata.outputs.data ).runner_arch }}
-        CDN_URL: ${{ inputs.cdn-url }}
-        ROCKSDB_VERSION: ${{ inputs.rocksdb-version }}
-      with:
-        dump-stdout: false
-        run: |
-          ROCKSDB_STATIC_LIB_ARCHIVE="rocksdb-static-lib-${ROCKSDB_VERSION}-${GH_RUNNER_OS}-${GH_RUNNER_ARCH}.tar.gz"
-          ROCKSDB_SHARED_LIB_ARCHIVE="rocksdb-shared-lib-${ROCKSDB_VERSION}-${GH_RUNNER_OS}-${GH_RUNNER_ARCH}.tar.gz"
-
-          ROCKSDB_LIB_PATH="${GITHUB_WORKSPACE}/rocksdb"
-
-          echo "Downloading static libs ${GH_RUNNER_OS}-${GH_RUNNER_ARCH}"
-          curl -LO --no-progress-meter "${CDN_URL}/rocksdb/${ROCKSDB_VERSION}/${ROCKSDB_STATIC_LIB_ARCHIVE}"
-
-          echo "Downloading shared libs ${GH_RUNNER_OS}-${GH_RUNNER_ARCH}"
-          curl -LO --no-progress-meter "${CDN_URL}/rocksdb/${ROCKSDB_VERSION}/${ROCKSDB_SHARED_LIB_ARCHIVE}"
-
-          mkdir -p "${ROCKSDB_LIB_PATH}"
-          echo "Unzip shared libs"
-          tar -zxf "${ROCKSDB_SHARED_LIB_ARCHIVE}" -C "${ROCKSDB_LIB_PATH}"
-          echo "Unzip static libs"
-          tar -zxf "${ROCKSDB_STATIC_LIB_ARCHIVE}" \
-            --strip-components=2 --wildcards --no-anchored -C "${ROCKSDB_LIB_PATH}/lib" '*.a'
-
-          ghwa_set_env PKG_CONFIG_PATH "${ROCKSDB_LIB_PATH}/lib/pkgconfig"
-          ghwa_set_env LD_LIBRARY_PATH "${ROCKSDB_LIB_PATH}/lib"
 
     - name: Run test command for the platform
       uses: milaboratory/github-ci/actions/shell@v4-beta
