add sanity check to artifact/restore action

diff --git a/actions/artifact/restore/action.yaml b/actions/artifact/restore/action.yaml
--- a/actions/artifact/restore/action.yaml
+++ b/actions/artifact/restore/action.yaml
@@ -77,10 +77,22 @@ runs:
         ARTIFACT_NAME: ${{ inputs.name }}
         ARCHIVE_NAME: ${{ steps.archive-name.outputs.name }}
       run: |
+        if ! [ -d "./artifacts-restore-5b3513f5" ]; then
+          echo "::error::No artifacts were restored by the action. Is 'name'/'pattern' input correct?" >&2
+          exit 1
+        fi
+
+        at_least_one_found=false
         find \
           "./artifacts-restore-5b3513f5" \
           -type f \
           -name "${ARCHIVE_NAME}.tar" |
           while read -r file; do
+            at_least_one_found=true
             tar -x -f "${file}"
           done
+
+        if ! ${at_least_one_found}; then
+          echo "::error::No artifacts were restored by the action. Only artifacts saved with 'artifact/save' action can be restored by 'artifact/restore'" >&2
+          exit 1
+        fi
