check artifact name is not empty

diff --git a/actions/artifact/restore/action.yaml b/actions/artifact/restore/action.yaml
--- a/actions/artifact/restore/action.yaml
+++ b/actions/artifact/restore/action.yaml
@@ -6,31 +6,31 @@ description: |
   on current agent, keeping all permissions and paths (relative to current WD)
 
 inputs:
-    name:
-      description: |
-        Name of the artifact to download.
-      required: true
+  name:
+    description: |
+      Name of the artifact to download.
+    required: true
 
-    github-token:
-      description: |
-        The GitHub token used to authenticate with the GitHub API.
-        This is required when downloading artifacts from a different repository or from a different workflow run.
-        Optional. If unspecified, the action will download artifacts from the current repo and the current workflow run.
-      required: false
+  github-token:
+    description: |
+      The GitHub token used to authenticate with the GitHub API.
+      This is required when downloading artifacts from a different repository or from a different workflow run.
+      Optional. If unspecified, the action will download artifacts from the current repo and the current workflow run.
+    required: false
 
-    repository:
-      description: |
-        The repository owner and the repository name joined together by "/".
-        If github-token is specified, this is the repository that artifacts will be downloaded from.
-        Optional. Default is {{ github.repository }}
-      required: false
+  repository:
+    description: |
+      The repository owner and the repository name joined together by "/".
+      If github-token is specified, this is the repository that artifacts will be downloaded from.
+      Optional. Default is {{ github.repository }}
+    required: false
 
-    run-id:
-      description: |
-        The id of the workflow run where the desired download artifact was uploaded from.
-        If github-token is specified, this is the run that artifacts will be downloaded from.
-        Optional. Default is {{ github.run_id }}
-      required: false
+  run-id:
+    description: |
+      The id of the workflow run where the desired download artifact was uploaded from.
+      If github-token is specified, this is the run that artifacts will be downloaded from.
+      Optional. Default is {{ github.run_id }}
+    required: false
 
 runs:
   using: "composite"
@@ -45,6 +45,11 @@ runs:
         # We need unique archive name here to not overwrite any existing file in workdir.
         # We also need static name to simplify 'restore' action logic.
         # This name is an attempt to meet both criteria.
+        if [ -z "ARTIFACT_NAME" ];
+          echo "::error::Empty 'name' input. Specify artifact name" >&2
+          exit 1
+        fi
+
         archive_name="artifact-$( echo "${ARTIFACT_NAME}" | sha256sum | awk '{print $1}' )"
         echo "name=${archive_name}" >> "${GITHUB_OUTPUT}"
 
diff --git a/actions/artifact/save/action.yaml b/actions/artifact/save/action.yaml
--- a/actions/artifact/save/action.yaml
+++ b/actions/artifact/save/action.yaml
@@ -71,13 +71,6 @@ runs:
   using: "composite"
 
   steps:
-    - uses: milaboratory/github-ci/actions/files/list@v4-beta
-      id: artifact-files
-      with:
-        patterns: ${{ inputs.path }}
-        exclude-hidden-files: ${{ ! fromJSON(inputs.include-hidden-files) }}
-        relative: true
-
     - name: Generate archive name
       id: archive-name
       shell: bash
@@ -87,8 +80,20 @@ runs:
         # We need unique archive name here to not overwrite any existing file in workdir.
         # We also need static name to simplify 'restore' action logic.
         # This name is an attempt to meet both criteria.
+        if [ -z "ARTIFACT_NAME" ];
+          echo "::error::Empty 'name' input. Specify artifact name" >&2
+          exit 1
+        fi
+
         archive_name="artifact-$( echo "${ARTIFACT_NAME}" | sha256sum | awk '{print $1}' )"
         echo "name=${archive_name}" >> "${GITHUB_OUTPUT}"
+
+    - uses: milaboratory/github-ci/actions/files/list@v4-beta
+      id: artifact-files
+      with:
+        patterns: ${{ inputs.path }}
+        exclude-hidden-files: ${{ ! fromJSON(inputs.include-hidden-files) }}
+        relative: true
 
     - name: Create tar
       shell: bash
