Merge to v4 2023 06 23 (#44)
* clean stale regression pr action
* add platform gui dependencies download
* add npm auth for node generic application

diff --git a/.github/workflows/platform-gui.yaml b/.github/workflows/platform-gui.yaml
--- a/.github/workflows/platform-gui.yaml
+++ b/.github/workflows/platform-gui.yaml
@@ -383,8 +383,22 @@ on:
         default: 'false'
 
       #
-      # Platform download
+      # Dependencies download control
       #
+      java-url:
+        description: |
+          JAVA download url.
+        type: string
+        required: false
+        default: 'https://corretto.aws/downloads/latest'
+
+      mixcr-url:
+        description: |
+          CDN url for MiXCR.
+        type: string
+        required: false
+        default: 'https://cdn.milaboratory.com/software/mixcr'
+
       pl-s3-iam-role-to-assume:
         description: |
           The ARN of a IAM role to assume and configure the Actions environment with
@@ -629,51 +643,119 @@ jobs:
           role-to-assume: ${{ inputs.pl-s3-iam-role-to-assume }}
           aws-region: ${{ inputs.pl-s3-region }}
 
-      - name: Get OS arch
-        id: os_arch
+      - name: Get platform gui dependecies
+        id: get_deps
         uses: milaboratory/github-ci/actions/shell@v4
+        env:
+          S3_BUKCET: ${{ inputs.pl-s3-bucket }}
+          JAVA_URL: ${{ inputs.java-url }}
+          MIXCR_URL: ${{ inputs.mixcr-url }}
         with:
           run: |
             get_os_arch=$(uname -m)
             case "${get_os_arch}" in
               x86_64)
-                echo "amd64"
+                _RUNNER_OS_ARCH="amd64"
+                _JAVA_ARCH="x64"
                 ;;
               aarch64 | arm64)
-                echo "arm64"
+                _RUNNER_OS_ARCH="arm64"
+                _JAVA_ARCH="aarch64"
                 ;;
               *)
                 echo "Arch is not in the list: ${get_os_arch}"
                 exit 1
                 ;;
             esac
+            
+            _RUNNER_OS_SANITEZED=$(echo ${RUNNER_OS} | awk '{print tolower($0)}')
 
-      - name: Download and unpack platform artifact
+            _PL_VERSION=$(jq -r ".dependencies.architecture.$_RUNNER_OS_ARCH.$_RUNNER_OS_SANITEZED[] | select(.name == \"pl\") | .version" plui-dependencies.json)
+            _MIXCR_VERSION=$(jq -r ".dependencies.common[] | select(.name == \"mixcr\") | .version" plui-dependencies.json)
+            _JAVA_VERSION=$(jq -r ".dependencies.common[] | select(.name == \"java\") | .version" plui-dependencies.json)
+
+            _PL_ARCHIVE="${_PL_VERSION}-${_RUNNER_OS_ARCH}.zip"
+            _PL_DL_LINK="s3://${S3_BUKCET}/pl/${_RUNNER_OS_SANITEZED}/${_PL_ARCHIVE}"
+
+            _MIXCR_ARCHIVE="${_MIXCR_VERSION}.zip"
+            _MIXCR_DL_LINK="${MIXCR_URL}/${_MIXCR_ARCHIVE}"
+
+            if [ "${_RUNNER_OS_SANITEZED}" == "windows" ];then
+              _JAVA_ARCHIVE="${_JAVA_VERSION}-${_JAVA_ARCH}-${_RUNNER_OS_SANITEZED}-jdk.zip"
+            else
+              _JAVA_ARCHIVE="${_JAVA_VERSION}-${_JAVA_ARCH}-${_RUNNER_OS_SANITEZED}-jdk.tar.gz"
+            fi
+            _JAVA_DL_LINK="${JAVA_URL}/${_JAVA_ARCHIVE}"
+
+            ghwa_set_output "pl-archive" "${_PL_ARCHIVE}"
+            ghwa_set_output "pl-dl-link" "${_PL_DL_LINK}"
+
+            ghwa_set_output "mixcr-archive" "${_MIXCR_ARCHIVE}"
+            ghwa_set_output "mixcr-dl-link" "${_MIXCR_DL_LINK}"
+
+            ghwa_set_output "java-archive" "${_JAVA_ARCHIVE}"
+            ghwa_set_output "java-dl-link" "${_JAVA_DL_LINK}"
+
+      - name: Prepare dependencies for platform gui
         uses: milaboratory/github-ci/actions/shell@v4
         env:
-          RUNNER_OS_ARCH: ${{ steps.os_arch.outputs.stdout }}
-          PL_DIST: "pl-dist"
-          PL_S3_BUKCET: ${{ inputs.pl-s3-bucket }}
+          PL_DIST_DIR: "pl-dist"
+          EXT_PROGRAMS_DIR: "external_programs"
+          TMP_DIR: "/tmp"
+          PL_ARCHIVE: ${{ fromJSON( steps.get_deps.outputs.data ).pl-archive }}
+          PL_DL_LINK: ${{ fromJSON( steps.get_deps.outputs.data ).pl-dl-link }}
+          MIXCR_ARCHIVE: ${{ fromJSON( steps.get_deps.outputs.data ).mixcr-archive }}
+          MIXCR_DL_LINK: ${{ fromJSON( steps.get_deps.outputs.data ).mixcr-dl-link }}
+          JAVA_ARCHIVE: ${{ fromJSON( steps.get_deps.outputs.data ).java-archive }}
+          JAVA_DL_LINK: ${{ fromJSON( steps.get_deps.outputs.data ).java-dl-link }}
         with:
           dump-stdout: false
           run: |
-            # get archive name from pl-version.json
-            RUNNER_OS_SANITEZED=$(echo ${RUNNER_OS} | awk '{print tolower($0)}')
-            PL_ARCHIVE_NAME=$(
-              jq -r --arg RUNNER_OS_SANITEZED "${RUNNER_OS_SANITEZED}" --arg RUNNER_OS_ARCH "${RUNNER_OS_ARCH}" '
-              .operating_systems[]
-              | select(.name == $RUNNER_OS_SANITEZED)
-              | .architectures[]
-              | select(.name == $RUNNER_OS_ARCH)
-              | .application_archive' pl-version.json
-            )
+            mkdir -v ./"${PL_DIST_DIR}"
+            echo "Downloading platform archive..."
+            aws s3 cp --no-progress "${PL_DL_LINK}" ./
+            if [ -f "${PL_ARCHIVE}" ];then
+                echo "Extracting platform archive..."
+                7z x "${PL_ARCHIVE}" -o"${PL_DIST_DIR}"
+            else
+                echo "Platform archive not found"
+                exit 1
+            fi
 
-            # download archive
-            aws s3 cp "s3://${PL_S3_BUKCET}/pl/${RUNNER_OS_SANITEZED}/${PL_ARCHIVE_NAME}" ./
+            mkdir -pv ./"${EXT_PROGRAMS_DIR}"
+            echo "Downloading mixcr archive..."
+            curl -LO --no-progress-meter "${MIXCR_DL_LINK}"
+            if [ -f "${MIXCR_ARCHIVE}" ];then
+              echo "Extracting mixcr archive..."
+              7z x "${MIXCR_ARCHIVE}" mixcr.jar -o"${EXT_PROGRAMS_DIR}"
+            else
+              echo "MiXCR archive not found"
+              exit 1
+            fi
 
-            # unpack archive
-            mkdir ./"${PL_DIST}" && \
-            7z x "${PL_ARCHIVE_NAME}" -o"${PL_DIST}"
+            mkdir -pv ./"${EXT_PROGRAMS_DIR}/amazon-corretto" && mkdir -pv "${TMP_DIR}/amazon-corretto"
+            echo "Download java archive..."
+            curl -LO --no-progress-meter "${JAVA_DL_LINK}"
+            if [ -f "${JAVA_ARCHIVE}" ];then
+              if [ "${RUNNER_OS}" == "Windows" ];then
+                echo "Extracting java archive..."
+                7z x "${JAVA_ARCHIVE}" -o"${TMP_DIR}/amazon-corretto"
+              else
+                echo "Extracting java archive..."
+                tar xf "${JAVA_ARCHIVE}" --strip-components=1 --directory "${TMP_DIR}/amazon-corretto"
+              fi
+            else
+              echo "Java archive not found"
+              exit 1
+            fi
+
+            if [ "${RUNNER_OS}" == "Windows" ];then
+                mv "${TMP_DIR}/amazon-corretto"/*/* "./${EXT_PROGRAMS_DIR}/amazon-corretto"
+            elif [ "${RUNNER_OS}" == "macOS" ];then
+                mv "${TMP_DIR}/amazon-corretto/Contents/Home"/* "./${EXT_PROGRAMS_DIR}/amazon-corretto"
+            else
+                mv "${TMP_DIR}/amazon-corretto"/* "./${EXT_PROGRAMS_DIR}/amazon-corretto"
+            fi
 
       - uses: milaboratory/github-ci/blocks/node/build/electron@v4
         with:
@@ -690,8 +772,6 @@ jobs:
           mac-notr-api-key: ${{ secrets.MAC_NOTR_API_KEY }}
           mac-notr-api-key-id: ${{ secrets.MAC_NOTR_API_KEY_ID }}
           mac-notr-api-key-issuer-id: ${{ secrets.MAC_NOTR_API_KEY_ISSUER_ID }}
-          win-sign-cert: ${{ secrets.WIN_SIGN_CERT }}
-          win-sign-cert-pwd: ${{ secrets.WIN_SIGN_CERT_PWD }}
           node-version: ${{ inputs.node-version }}
           cache-version: ${{ inputs.cache-version }}
           registry-url: ${{ inputs.registry-url }}
