refator pl prepare dependecies step

diff --git a/.github/workflows/platform-gui.yaml b/.github/workflows/platform-gui.yaml
--- a/.github/workflows/platform-gui.yaml
+++ b/.github/workflows/platform-gui.yaml
@@ -643,20 +643,24 @@ jobs:
           role-to-assume: ${{ inputs.pl-s3-iam-role-to-assume }}
           aws-region: ${{ inputs.pl-s3-region }}
 
-      - name: Get OS arch
-        id: os_arch
+      - name: Get platform gui dependecies
+        id: get_deps
         uses: milaboratory/github-ci/actions/shell@v4-beta
+        env:
+          S3_BUKCET: ${{ inputs.pl-s3-bucket }}
+          JAVA_URL: ${{ inputs.java-url }}
+          MIXCR_URL: ${{ inputs.mixcr-url }}
         with:
           run: |
             get_os_arch=$(uname -m)
             case "${get_os_arch}" in
               x86_64)
-                ghwa_set_output "runner_os_arch" "amd64"
-                ghwa_set_output "java_arch" "x64"
+                _RUNNER_OS_ARCH="amd64"
+                _JAVA_ARCH="x64"
                 ;;
               aarch64 | arm64)
-                ghwa_set_output "runner_os_arch" "arm64"
-                ghwa_set_output "java_arch" "aarch64"
+                _RUNNER_OS_ARCH="arm64"
+                _JAVA_ARCH="aarch64"
                 ;;
               *)
                 echo "Arch is not in the list: ${get_os_arch}"
@@ -664,54 +668,94 @@ jobs:
                 ;;
             esac
 
-      - name: Download and unpack platform gui dependencies
+            _RUNNER_OS_SANITEZED=$(echo ${RUNNER_OS} | awk '{print tolower($0)}')
+
+            _PL_VERSION=$(jq -r ".dependencies.architecture.$_RUNNER_OS_ARCH.$_RUNNER_OS_SANITEZED[] | select(.name == \"pl\") | .version" plui-dependencies.json)
+            _MIXCR_VERSION=$(jq -r ".dependencies.common[] | select(.name == \"mixcr\") | .version" plui-dependencies.json)
+            _JAVA_VERSION=$(jq -r ".dependencies.common[] | select(.name == \"java\") | .version" plui-dependencies.json)
+
+            _PL_ARCHIVE="${_PL_VERSION}-${_RUNNER_OS_SANITEZE}.zip"
+            _PL_DL_LINK="s3://${S3_BUKCET}/pl/${_RUNNER_OS_SANITEZED}/${_PL_ARCHIVE}"
+
+            _MIXCR_ARCHIVE="${_MIXCR_VERSION}.zip"
+            _MIXCR_DL_LINK="${MIXCR_URL}/${_MIXCR_ARCHIVE}"
+
+            if [ "${_RUNNER_OS_SANITEZED}" == "windows" ];then
+              _JAVA_ARCHIVE="${_JAVA_VERSION}-${_JAVA_ARCH}-${_RUNNER_OS_SANITEZED}-jdk.zip"
+            else
+              _JAVA_ARCHIVE="${_JAVA_VERSION}-${_JAVA_ARCH}-${_RUNNER_OS_SANITEZED}-jdk.tar.gz"
+            fi
+            _JAVA_DL_LINK="${JAVA_URL}/${_JAVA_ARCHIVE}"
+
+            ghwa_set_output "pl-archive" "${_PL_ARCHIVE}"
+            ghwa_set_output "pl-dl-link" "${_PL_DL_LINK}"
+
+            ghwa_set_output "mixcr-archive" "${_MIXCR_ARCHIVE}"
+            ghwa_set_output "mixcr-dl-link" "${_MIXCR_DL_LINK}"
+
+            ghwa_set_output "java-archive" "${_JAVA_ARCHIVE}"
+            ghwa_set_output "java-dl-link" "${_JAVA_DL_LINK}"
+
+      - name: Prepare dependencies for platform gui
         uses: milaboratory/github-ci/actions/shell@v4-beta
         env:
-          RUNNER_OS_ARCH: ${{ fromJSON( steps.os_arch.outputs.data ).runner_os_arch }}
-          JAVA_ARCH: ${{ fromJSON( steps.os_arch.outputs.data ).java_arch }}
           PL_DIST_DIR: "pl-dist"
           EXT_PROGRAMS_DIR: "external_programs"
-          PL_S3_BUKCET: ${{ inputs.pl-s3-bucket }}
-          JAVA_URL: ${{ inputs.java-url }}
-          MIXCR_URL: ${{ inputs.mixcr-url }}
+          TMP_DIR: "/tmp"
+          PL_ARCHIVE: ${{ fromJSON( steps.get_deps.outputs.data ).pl-archive }}
+          PL_DL_LINK: ${{ fromJSON( steps.get_deps.outputs.data ).pl-dl-link }}
+          MIXCR_ARCHIVE: ${{ fromJSON( steps.get_deps.outputs.data ).mixcr-archive }}
+          MIXCR_DL_LINK: ${{ fromJSON( steps.get_deps.outputs.data ).mixcr-dl-link }}
+          JAVA_ARCHIVE: ${{ fromJSON( steps.get_deps.outputs.data ).java-archive }}
+          JAVA_DL_LINK: ${{ fromJSON( steps.get_deps.outputs.data ).java-dl-link }}
         with:
           dump-stdout: false
           run: |
-            # get dependencies versions from plui-dependencies.json
-            RUNNER_OS_SANITEZED=$(echo ${RUNNER_OS} | awk '{print tolower($0)}')
-            PL_VERSION=$(jq -r ".dependencies.architecture.$RUNNER_OS_ARCH.$RUNNER_OS_SANITEZED[] | select(.name == \"pl\") | .version" plui-dependencies.json)
-            MIXCR_VERSION=$(jq -r ".dependencies.common[] | select(.name == \"mixcr\") | .version" plui-dependencies.json)
-            JAVA_VERSION=$(jq -r ".dependencies.common[] | select(.name == \"java\") | .version" plui-dependencies.json)
-
-            # download pl
-            aws s3 cp "s3://${PL_S3_BUKCET}/pl/${RUNNER_OS_SANITEZED}/${PL_VERSION}-${RUNNER_OS_ARCH}.zip" ./
-
-            # unpack pl
-            mkdir -v ./"${PL_DIST_DIR}" && \
-            7z x "${PL_VERSION}-${RUNNER_OS_ARCH}.zip" -o"${PL_DIST_DIR}"
-
-            # create external programs directory
-            mkdir -v ./"${EXT_PROGRAMS_DIR}"
-            # download and unpack mixcr
-            wget -nv "${MIXCR_URL}/${MIXCR_VERSION}.zip"
-            7z x "${MIXCR_VERSION}.zip" mixcr.jar -o"${EXT_PROGRAMS_DIR}"
-
-            # download and unpack java
-            mkdir -pv ./"${EXT_PROGRAMS_DIR}/amazon-corretto" && mkdir -pv /tmp/amazon-corretto
-            if [ "${RUNNER_OS_SANITEZED}" == "windows" ];then
-              wget -nv "${JAVA_URL}/${JAVA_VERSION}-${JAVA_ARCH}-${RUNNER_OS_SANITEZED}.zip
-              7z x "${JAVA_VERSION}-${JAVA_ARCH}-${RUNNER_OS_SANITEZED}.zip -o"/tmp/amazon-corretto"
-              mv "/tmp/amazon-corretto/*/*" "${EXT_PROGRAMS_DIR}/amazon-corretto/"
+            mkdir -v ./"${PL_DIST_DIR}"
+            echo "Downloading platform archive..."
+            aws s3 cp --no-progress "${PL_DL_LINK}" ./
+            if [ -f "${PL_ARCHIVE}" ];then
+                echo "Extracting platform archive..."
+                7z x "${PL_ARCHIVE}" -o"${PL_DIST_DIR}"
             else
-              wget -nv "${JAVA_URL}/${JAVA_VERSION}-${JAVA_ARCH}-${RUNNER_OS_SANITEZED}-jdk.tar.gz"
-              tar xvf "${JAVA_VERSION}-${JAVA_ARCH}-${RUNNER_OS_SANITEZED}-jdk.tar.gz" --strip-components=1 --directory "/tmp/amazon-corretto"
-              if [ "${RUNNER_OS_SANITEZED}" == "macos" ];then
-                  mv "/tmp/amazon-corretto/Contents/Home"/* "./${EXT_PROGRAMS_DIR}/amazon-corretto"
-              else
-                  mv "/tmp/amazon-corretto"/* "./${EXT_PROGRAMS_DIR}/amazon-corretto/"
-              fi
+                echo "Platform archive not found"
+                exit 1
             fi
 
+            mkdir -pv ./"${EXT_PROGRAMS_DIR}"
+            echo "Downloading mixcr archive..."
+            curl -LO --no-progress-meter "${MIXCR_DL_LINK}
+            if [ -f "${MIXCR_ARCHIVE}" ];then
+              echo "Extracting mixcr archive..."
+              7z x "${MIXCR_ARCHIVE}" mixcr.jar -o"${EXT_PROGRAMS_DIR}"
+            else
+              echo "MiXCR archive not found"
+              exit 1
+            fi
+
+            mkdir -pv ./"${EXT_PROGRAMS_DIR}/amazon-corretto" && mkdir -pv "${TMP_DIR}/amazon-corretto"
+            echo "Download java archive..."
+            curl -LO --no-progress-meter "${JAVA_DL_LINK}"
+            if [ -f "${JAVA_ARCHIVE}" ];then
+              if [ "${RUNNER_OS}" == "Windows ];then
+                echo "Extracting java archive..."
+                7z x "${JAVA_ARCHIVE} -o"${TMP_DIR}/amazon-corretto"
+              else
+                echo "Extracting java archive..."
+                tar xf "${JAVA_ARCHIVE}" --strip-components=1 --directory "${TMP_DIR}/amazon-corretto"
+              fi
+            else
+              echo "Java archive not found"
+              exit 1
+            fi
+
+            if [ "${RUNNER_OS}" == "Windows" ];then
+                mv "${TMP_DIR}/amazon-corretto"/*/* "./${EXT_PROGRAMS_DIR}/amazon-corretto"
+            elif [ "${RUNNER_OS}" == "macOS" ];then
+                mv "${TMP_DIR}/amazon-corretto/Contents/Home"/* "./${EXT_PROGRAMS_DIR}/amazon-corretto"
+            else
+                mv "${TMP_DIR}/amazon-corretto"/* "./${EXT_PROGRAMS_DIR}/amazon-corretto"
+            fi
 
       - uses: milaboratory/github-ci/blocks/node/build/electron@v4-beta
         with:
